# Generated by Django 5.0.6 on 2024-07-05 07:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delightsapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
