# Generated by Django 5.0.6 on 2024-07-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delightsapp", "0002_ingredient_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
