# Generated by Django 5.0.6 on 2024-07-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delightsapp", "0003_alter_ingredient_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="quantity",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="reciperequirement",
            name="quantity",
            field=models.FloatField(default=1),
        ),
    ]
