# Generated by Django 5.0.6 on 2024-07-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delightsapp", "0004_alter_ingredient_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
