# Generated by Django 5.0.6 on 2024-07-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delightsapp", "0005_alter_menuitem_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="cost",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="weight",
            field=models.FloatField(default=1.2),
        ),
    ]
