# Generated by Django 5.0.6 on 2024-07-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delightsapp", "0006_menuitem_cost_menuitem_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
